version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Starting deletion of existing build
      - aws s3 rm s3://profileimages-1306/package/Hello-World/target/ || true
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
#      - aws s3 cp target/hello-world-1.0.jar s3://profileimages-1306/package/
artifacts:
  files:
    - target/hello-world-1.0.jar
